export const NewArrivalProductSampleData = [
    {
        id: 1,
        imgSrc: "newArrival1.png",
        productName: "Shiny Dress",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 5,
        category: "Women's Fashion",
    },
    {
        id: 2,
        imgSrc: "newArrival2.png",
        productName: "Long Dress",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 4,
        category: "Women's Fashion",
    },
    {
        id: 3,
        imgSrc: "newArrival3.png",
        productName: "Full Sweater",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 5,
        category: "Men's Fashion",
    },
    {
        id: 4,
        imgSrc: "newArrival4.png",
        productName: "White Dress",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 4,
        category: "Women's Fashion",
    },
    {
        id: 5,
        imgSrc: "newArrival5.png",
        productName: "Colorful Dress",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 3,
        category: "Women Accessories",
    },
    {
        id: 6,
        imgSrc: "newArrival6.png",
        productName: "White Shirt",
        brandName: "Al Karam",
        reviews: "4.1k",
        price: "95.50",
        status: "Almost Sold Out",
        rating: 5,
        category: "Men Accessories",
    },
];