export const sampleDataFeedBackCard = [
    {
        id: 1,
        imgSrc: 'customer1.png',
        feedback: "You won't regret it. I would like to personally thank you for your outstanding product. Absolutely wonderful!",
        name: 'James K.',
        carrer: 'Traveler',
        rating: 5,
    },
    {
        id: 2,
        imgSrc: 'customer2.png',
        feedback: "This is exactly what I was looking for. Thank you for making it painless, pleasant, and most of all hassle-free!",
        name: 'Susan W.',
        carrer: 'Designer',
        rating: 4,
    },
    {
        id: 3,
        imgSrc: 'customer3.png',
        feedback: "I am so pleased with this product. It's the most valuable business resource we have EVER purchased.",
        name: 'John D.',
        carrer: 'Entrepreneur',
        rating: 5,
    },
    {
        id: 4,
        imgSrc: 'defaultImg.jpg',
        feedback: "I am so pleased with this product. It's the most valuable business resource we have EVER purchased.",
        name: 'John H.',
        carrer: 'Entrepreneur',
        rating: 5,
    },
    {
        id: 5,
        imgSrc: 'hieu.jpg',
        feedback: "I am so pleased with this product. It's the most valuable business resource we have EVER purchased.",
        name: 'Gia H.',
        carrer: 'Entrepreneur',
        rating: 5,
    },
];